services:
  SPlayer:
    build:
      context: .
    image: lcymusicpro
    container_name: LCYMusicPro
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 7899:7899
    restart: always
